### ISSUE TITLE
Question: error flag in `rmqamqp::TopologyTransformer::processReplyMessage`

### ISSUE THREAD

**Issue by 678098** [bloomberg/rmqcpp#12]
Here the code just returns `false` without setting the error flag `d_error`:
https://github.com/bloomberg/rmqcpp/blob/becec1737669dbebb0a108e9dd0244b294951633/src/rmq/rmqamqp/rmqamqp_topologytransformer.cpp#L114-L116

In other places in this procedure the error flag is set to true when some problem occurs, for example:
https://github.com/bloomberg/rmqcpp/blob/becec1737669dbebb0a108e9dd0244b294951633/src/rmq/rmqamqp/rmqamqp_topologytransformer.cpp#L118-L123

Is it intended behaviour in the first code example? So, basically, returning with `false` there is not an error situation?

**Comment by willhoy** [comment]
Good catch, I think initially there was no such variable and this method would return whether there was an error or not, so it wasn't required, but later added for performing updates, it should be safe to set it here.
