### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by stridersheir** [bloomberg/rmqcpp#22]
Your project currently lacks any versioning, could you create versioning to support long term use and installation?

**Comment by adamncasey** [comment]
Thanks for reaching out @stridersheir !

Internally we don't have particularly meaningful version numbers, users more or less just get the latest version. With that in mind, we'll run this project with the expectation that `main` is releasable at any point in time.

But that said, we are [publishing rmqcpp to vcpkg](https://github.com/microsoft/vcpkg/pull/34797/files), and that will have version numbers. Are version numbers in vcpkg sufficient for your usage?

**Comment by adamncasey** [comment]
https://github.com/bloomberg/rmqcpp/releases 1.0.0 has been labelled on github.com
