### ISSUE TITLE
vcpkg bde dependencies (and why not ntf-core)

### ISSUE THREAD

**Issue by rmanaloto-tastytrade** [bloomberg/rmqcpp#40]
**Is your feature request related to a problem? Please describe.**
I'm reviewing this library to incorporate into my system and had a few initial questions. 

1. Given that this library has a dependency on bde, would it be possible to get bde updated in vcpkg's ports? I'm not sure which version of bde is being used internally at Bloomberg for this project.
2. Why was boost-asio chosen as the socket library vs your internal ntf-core library?

**Describe the solution you'd like**
Updates to bde vcpkg port and just initial queries about the library

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ahsanabbas123** [comment]
Hi, the port for `rmqcpp` at https://github.com/microsoft/vcpkg/blob/master/ports/rmqcpp/vcpkg.json#L9 mentions the `bde` version requirements - it would use the latest external version on building (and has to be `>3.123.0.0`).

For the second question - `boost-asio` did the job well and the rest would be above my pay grade :)
